// A deterministic owner world for scan tests. Same rows on libSQL and D1 so both runtimes must
// derive identical notifications. Synthetic identifiers only.
import type { Db } from '../src/db/client';
import * as s from '../src/db/schema';

export async function seedOwnerWorld(db: Db, now: string) {
  await db.batch([
    db
      .insert(s.memberships)
      .values({ id: 'm-isc2', bodyId: 'isc2', memberNumber: 'TEST-0', since: '2023-09-11' }),
    db.insert(s.heldCertifications).values({
      id: 'h-cissp',
      certificationId: 'isc2/cissp',
      certNumber: 'TEST-CISSP',
      earnedOn: '2025-09-11',
      status: 'active',
      notes: null,
    }),
    db.insert(s.heldCertifications).values({
      id: 'h-secplus',
      certificationId: 'comptia/security-plus',
      certNumber: 'TEST-SEC',
      earnedOn: '2023-10-07',
      status: 'active',
      notes: null,
    }),
    // CISSP cycle: AMF period 2 started 2026-09-11 (yesterday relative to 2026-09-12) and is unpaid.
    db.insert(s.cycles).values({
      id: 'cy-cissp',
      heldCertId: 'h-cissp',
      sequence: 1,
      startsOn: '2025-09-11',
      endsOn: '2028-09-11',
      ruleVersionId: 'isc2@1',
      status: 'open',
    }),
    db.insert(s.payments).values({
      id: 'p1',
      targetType: 'membership',
      targetId: 'm-isc2',
      periodStart: '2025-09-11',
      periodEnd: '2026-09-11',
      dueOn: '2025-09-11',
      amountCents: 13500,
      currency: 'USD',
      paidOn: '2025-09-11',
      confirmationRef: null,
      status: 'paid',
      waiveReason: null,
    }),
    // Security+: a renewed first cycle (kept) and an open second cycle ending in 25 days.
    db.insert(s.cycles).values({
      id: 'cy-renewed',
      heldCertId: 'h-secplus',
      sequence: 1,
      startsOn: '2020-10-07',
      endsOn: '2023-10-07',
      ruleVersionId: 'comptia@1',
      status: 'renewed',
    }),
    db.insert(s.cycles).values({
      id: 'cy-secplus',
      heldCertId: 'h-secplus',
      sequence: 2,
      startsOn: '2023-10-07',
      endsOn: '2026-10-07',
      ruleVersionId: 'comptia@1',
      status: 'open',
    }),
    db.insert(s.payments).values({
      id: 'p2',
      targetType: 'cycle',
      targetId: 'cy-secplus',
      periodStart: '2023-10-07',
      periodEnd: '2026-10-07',
      dueOn: '2023-10-07',
      amountCents: 15000,
      currency: 'USD',
      paidOn: '2023-10-07',
      confirmationRef: null,
      status: 'paid',
      waiveReason: null,
    }),
    db.insert(s.activities).values({
      id: 'a-old',
      title: 'Old course',
      occurredOn: '2022-01-01',
      provider: null,
      durationMinutes: 600,
      itemCount: 1,
      activityType: 'attend_training',
      description: null,
      source: 'import',
      status: 'logged',
      createdAt: now,
    }),
    db.insert(s.creditApplications).values({
      id: 'ca-old',
      activityId: 'a-old',
      heldCertId: 'h-secplus',
      cycleId: 'cy-renewed',
      creditsX100: 1000,
      categoryKey: null,
      status: 'accepted',
      ruleVersionId: 'comptia@1',
      creditingRuleId: null,
      suggestedCreditsX100: null,
      overrideReason: 'imported',
      explanation: null,
    }),
    db.insert(s.activities).values({
      id: 'a-new',
      title: 'Course',
      occurredOn: '2024-05-01',
      provider: null,
      durationMinutes: 3000,
      itemCount: 1,
      activityType: 'attend_training',
      description: null,
      source: 'import',
      status: 'logged',
      createdAt: now,
    }),
    db.insert(s.creditApplications).values({
      id: 'ca-new',
      activityId: 'a-new',
      heldCertId: 'h-secplus',
      cycleId: 'cy-secplus',
      creditsX100: 5000,
      categoryKey: null,
      status: 'accepted',
      ruleVersionId: 'comptia@1',
      creditingRuleId: null,
      suggestedCreditsX100: null,
      overrideReason: 'imported',
      explanation: null,
    }),
  ]);
}
