-- Seed aws@1: generated by scripts/compile-catalog.ts from catalog/bodies/aws.yaml. Do not edit.
INSERT INTO `bodies` (`id`, `name`, `website`, `fee_scope`) VALUES ('aws', 'Amazon Web Services', 'https://aws.amazon.com/certification', 'none') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('aws/cloud-practitioner', 'aws', 'AWS Certified Cloud Practitioner', 'CLF', 'credit', 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('aws/solutions-architect-associate', 'aws', 'AWS Certified Solutions Architect – Associate', 'SAA', 'credit', 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('aws/developer-associate', 'aws', 'AWS Certified Developer – Associate', 'DVA', 'credit', 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('aws/cloudops-associate', 'aws', 'AWS Certified CloudOps Engineer – Associate', 'SOA', 'credit', 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('aws/security-specialty', 'aws', 'AWS Certified Security – Specialty', 'SCS', 'credit', 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('aws/solutions-architect-professional', 'aws', 'AWS Certified Solutions Architect – Professional', 'SAP', 'credit', 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('aws/devops-engineer-professional', 'aws', 'AWS Certified DevOps Engineer – Professional', 'DOP', 'credit', 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `rule_versions` (`id`, `body_id`, `version`, `effective_from`, `source_url`, `source_title`, `verified_on`, `notes`) VALUES ('aws@1', 'aws', 1, '2025-01-01', 'https://aws.amazon.com/certification/recertification/', 'AWS Certification — Recertification', '2026-09-12', 'Three years, renewed by passing the latest version of the same exam or a higher-level exam (recert_exam). Higher-level relations encoded as earning_renews. AWS also offers a one-year ''maintenance'' extension through paid Skill Builder activities — not modelled. No maintenance fee; the exam fee carries a 50% voucher.') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_requirements` (`id`, `rule_version_id`, `certification_id`, `cycle_months`, `total_credits_x100`, `annual_min_x100`, `annual_min_severity`, `fee_amount_cents`, `fee_currency`, `fee_period_months`, `fee_params`) VALUES ('aws@1/aws/cloud-practitioner', 'aws@1', 'aws/cloud-practitioner', 36, 0, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_requirements` (`id`, `rule_version_id`, `certification_id`, `cycle_months`, `total_credits_x100`, `annual_min_x100`, `annual_min_severity`, `fee_amount_cents`, `fee_currency`, `fee_period_months`, `fee_params`) VALUES ('aws@1/aws/solutions-architect-associate', 'aws@1', 'aws/solutions-architect-associate', 36, 0, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_requirements` (`id`, `rule_version_id`, `certification_id`, `cycle_months`, `total_credits_x100`, `annual_min_x100`, `annual_min_severity`, `fee_amount_cents`, `fee_currency`, `fee_period_months`, `fee_params`) VALUES ('aws@1/aws/developer-associate', 'aws@1', 'aws/developer-associate', 36, 0, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_requirements` (`id`, `rule_version_id`, `certification_id`, `cycle_months`, `total_credits_x100`, `annual_min_x100`, `annual_min_severity`, `fee_amount_cents`, `fee_currency`, `fee_period_months`, `fee_params`) VALUES ('aws@1/aws/cloudops-associate', 'aws@1', 'aws/cloudops-associate', 36, 0, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_requirements` (`id`, `rule_version_id`, `certification_id`, `cycle_months`, `total_credits_x100`, `annual_min_x100`, `annual_min_severity`, `fee_amount_cents`, `fee_currency`, `fee_period_months`, `fee_params`) VALUES ('aws@1/aws/security-specialty', 'aws@1', 'aws/security-specialty', 36, 0, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_requirements` (`id`, `rule_version_id`, `certification_id`, `cycle_months`, `total_credits_x100`, `annual_min_x100`, `annual_min_severity`, `fee_amount_cents`, `fee_currency`, `fee_period_months`, `fee_params`) VALUES ('aws@1/aws/solutions-architect-professional', 'aws@1', 'aws/solutions-architect-professional', 36, 0, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_requirements` (`id`, `rule_version_id`, `certification_id`, `cycle_months`, `total_credits_x100`, `annual_min_x100`, `annual_min_severity`, `fee_amount_cents`, `fee_currency`, `fee_period_months`, `fee_params`) VALUES ('aws@1/aws/devops-engineer-professional', 'aws@1', 'aws/devops-engineer-professional', 36, 0, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `constraints` (`id`, `rule_version_id`, `certification_id`, `type`, `params`, `severity`) VALUES ('aws@1/con/001-recert_exam', 'aws@1', NULL, 'recert_exam', '{}', 'hard') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_relations` (`id`, `rule_version_id`, `from_cert_id`, `to_cert_id`, `relation`, `credits_x100`) VALUES ('aws@1/rel/001', 'aws@1', 'aws/solutions-architect-associate', 'aws/cloud-practitioner', 'earning_renews', NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_relations` (`id`, `rule_version_id`, `from_cert_id`, `to_cert_id`, `relation`, `credits_x100`) VALUES ('aws@1/rel/002', 'aws@1', 'aws/developer-associate', 'aws/cloud-practitioner', 'earning_renews', NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_relations` (`id`, `rule_version_id`, `from_cert_id`, `to_cert_id`, `relation`, `credits_x100`) VALUES ('aws@1/rel/003', 'aws@1', 'aws/cloudops-associate', 'aws/cloud-practitioner', 'earning_renews', NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_relations` (`id`, `rule_version_id`, `from_cert_id`, `to_cert_id`, `relation`, `credits_x100`) VALUES ('aws@1/rel/004', 'aws@1', 'aws/solutions-architect-professional', 'aws/cloud-practitioner', 'earning_renews', NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_relations` (`id`, `rule_version_id`, `from_cert_id`, `to_cert_id`, `relation`, `credits_x100`) VALUES ('aws@1/rel/005', 'aws@1', 'aws/devops-engineer-professional', 'aws/cloud-practitioner', 'earning_renews', NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_relations` (`id`, `rule_version_id`, `from_cert_id`, `to_cert_id`, `relation`, `credits_x100`) VALUES ('aws@1/rel/006', 'aws@1', 'aws/solutions-architect-professional', 'aws/solutions-architect-associate', 'earning_renews', NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_relations` (`id`, `rule_version_id`, `from_cert_id`, `to_cert_id`, `relation`, `credits_x100`) VALUES ('aws@1/rel/007', 'aws@1', 'aws/devops-engineer-professional', 'aws/developer-associate', 'earning_renews', NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_relations` (`id`, `rule_version_id`, `from_cert_id`, `to_cert_id`, `relation`, `credits_x100`) VALUES ('aws@1/rel/008', 'aws@1', 'aws/devops-engineer-professional', 'aws/cloudops-associate', 'earning_renews', NULL) ON CONFLICT DO NOTHING;
