-- Seed cisco@1: generated by scripts/compile-catalog.ts from catalog/bodies/cisco.yaml. Do not edit.
INSERT INTO `bodies` (`id`, `name`, `website`, `fee_scope`) VALUES ('cisco', 'Cisco', 'https://www.cisco.com', 'none') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('cisco/ccna', 'cisco', 'Cisco Certified Network Associate', 'CCNA', 'CE credit', 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('cisco/ccnp-security', 'cisco', 'Cisco Certified Network Professional Security', 'CCNP Security', 'CE credit', 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('cisco/ccnp-enterprise', 'cisco', 'Cisco Certified Network Professional Enterprise', 'CCNP Enterprise', 'CE credit', 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('cisco/cyberops-associate', 'cisco', 'Cisco Certified CyberOps Associate', 'CyberOps Associate', 'CE credit', 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('cisco/ccie-security', 'cisco', 'Cisco Certified Internetwork Expert Security', 'CCIE Security', 'CE credit', 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `rule_versions` (`id`, `body_id`, `version`, `effective_from`, `source_url`, `source_title`, `verified_on`, `notes`) VALUES ('cisco@1', 'cisco', 1, '2025-07-15', 'https://www.cisco.com/c/en/us/training-events/training-certifications/recertification-policy.html', 'Cisco Recertification Policy', '2026-09-12', 'Three-year validity. Recertify by earning the level''s CE credits OR by passing the qualifying exam(s) (any_of). CE credits are assigned per approved activity in the Cisco CE portal, not per hour — apply by override with the portal''s value. No fee is disclosed for the CE program.') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_requirements` (`id`, `rule_version_id`, `certification_id`, `cycle_months`, `total_credits_x100`, `annual_min_x100`, `annual_min_severity`, `fee_amount_cents`, `fee_currency`, `fee_period_months`, `fee_params`) VALUES ('cisco@1/cisco/ccna', 'cisco@1', 'cisco/ccna', 36, 3000, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_requirements` (`id`, `rule_version_id`, `certification_id`, `cycle_months`, `total_credits_x100`, `annual_min_x100`, `annual_min_severity`, `fee_amount_cents`, `fee_currency`, `fee_period_months`, `fee_params`) VALUES ('cisco@1/cisco/cyberops-associate', 'cisco@1', 'cisco/cyberops-associate', 36, 3000, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_requirements` (`id`, `rule_version_id`, `certification_id`, `cycle_months`, `total_credits_x100`, `annual_min_x100`, `annual_min_severity`, `fee_amount_cents`, `fee_currency`, `fee_period_months`, `fee_params`) VALUES ('cisco@1/cisco/ccnp-security', 'cisco@1', 'cisco/ccnp-security', 36, 8000, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_requirements` (`id`, `rule_version_id`, `certification_id`, `cycle_months`, `total_credits_x100`, `annual_min_x100`, `annual_min_severity`, `fee_amount_cents`, `fee_currency`, `fee_period_months`, `fee_params`) VALUES ('cisco@1/cisco/ccnp-enterprise', 'cisco@1', 'cisco/ccnp-enterprise', 36, 8000, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_requirements` (`id`, `rule_version_id`, `certification_id`, `cycle_months`, `total_credits_x100`, `annual_min_x100`, `annual_min_severity`, `fee_amount_cents`, `fee_currency`, `fee_period_months`, `fee_params`) VALUES ('cisco@1/cisco/ccie-security', 'cisco@1', 'cisco/ccie-security', 36, 12000, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `constraints` (`id`, `rule_version_id`, `certification_id`, `type`, `params`, `severity`) VALUES ('cisco@1/con/001-any_of', 'cisco@1', NULL, 'any_of', '{"of":[{"type":"cycle_total"},{"type":"recert_exam"}]}', 'hard') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_relations` (`id`, `rule_version_id`, `from_cert_id`, `to_cert_id`, `relation`, `credits_x100`) VALUES ('cisco@1/rel/001', 'cisco@1', 'cisco/ccnp-security', 'cisco/ccna', 'earning_renews', NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_relations` (`id`, `rule_version_id`, `from_cert_id`, `to_cert_id`, `relation`, `credits_x100`) VALUES ('cisco@1/rel/002', 'cisco@1', 'cisco/ccnp-enterprise', 'cisco/ccna', 'earning_renews', NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_relations` (`id`, `rule_version_id`, `from_cert_id`, `to_cert_id`, `relation`, `credits_x100`) VALUES ('cisco@1/rel/003', 'cisco@1', 'cisco/ccie-security', 'cisco/ccnp-security', 'earning_renews', NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_relations` (`id`, `rule_version_id`, `from_cert_id`, `to_cert_id`, `relation`, `credits_x100`) VALUES ('cisco@1/rel/004', 'cisco@1', 'cisco/ccie-security', 'cisco/ccna', 'earning_renews', NULL) ON CONFLICT DO NOTHING;
