-- Seed giac@1: generated by scripts/compile-catalog.ts from catalog/bodies/giac.yaml. Do not edit.
INSERT INTO `bodies` (`id`, `name`, `website`, `fee_scope`) VALUES ('giac', 'GIAC', 'https://www.giac.org', 'certification') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('giac/gsec', 'giac', 'GIAC Security Essentials', 'GSEC', 'CPE', 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('giac/gcih', 'giac', 'GIAC Certified Incident Handler', 'GCIH', 'CPE', 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('giac/gcia', 'giac', 'GIAC Certified Intrusion Analyst', 'GCIA', 'CPE', 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('giac/gcfa', 'giac', 'GIAC Certified Forensic Analyst', 'GCFA', 'CPE', 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('giac/gpen', 'giac', 'GIAC Penetration Tester', 'GPEN', 'CPE', 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `rule_versions` (`id`, `body_id`, `version`, `effective_from`, `source_url`, `source_title`, `verified_on`, `notes`) VALUES ('giac@1', 'giac', 1, '2025-01-01', 'https://www.giac.org/pdfs/cert-renewal/SANS-GIAC-Certification-Renewal-Brochure-How-To.pdf', 'GIAC Certification Renewal How-To Guide', '2026-09-12', 'Four-year cycle; 36 CPEs OR retake the exam (any_of). Renewal fee $499 per certification per four-year term, paid any time from the two-year mark; additional renewals registered within the following two years are $249 (fee_params). Per-hour crediting rates are not published — only category maxima — so no crediting rules are seeded; use overrides with the value GIAC accepted.') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_requirements` (`id`, `rule_version_id`, `certification_id`, `cycle_months`, `total_credits_x100`, `annual_min_x100`, `annual_min_severity`, `fee_amount_cents`, `fee_currency`, `fee_period_months`, `fee_params`) VALUES ('giac@1/giac/gsec', 'giac@1', 'giac/gsec', 48, 3600, NULL, NULL, 49900, 'USD', 48, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_requirements` (`id`, `rule_version_id`, `certification_id`, `cycle_months`, `total_credits_x100`, `annual_min_x100`, `annual_min_severity`, `fee_amount_cents`, `fee_currency`, `fee_period_months`, `fee_params`) VALUES ('giac@1/giac/gcih', 'giac@1', 'giac/gcih', 48, 3600, NULL, NULL, 49900, 'USD', 48, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_requirements` (`id`, `rule_version_id`, `certification_id`, `cycle_months`, `total_credits_x100`, `annual_min_x100`, `annual_min_severity`, `fee_amount_cents`, `fee_currency`, `fee_period_months`, `fee_params`) VALUES ('giac@1/giac/gcia', 'giac@1', 'giac/gcia', 48, 3600, NULL, NULL, 49900, 'USD', 48, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_requirements` (`id`, `rule_version_id`, `certification_id`, `cycle_months`, `total_credits_x100`, `annual_min_x100`, `annual_min_severity`, `fee_amount_cents`, `fee_currency`, `fee_period_months`, `fee_params`) VALUES ('giac@1/giac/gcfa', 'giac@1', 'giac/gcfa', 48, 3600, NULL, NULL, 49900, 'USD', 48, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_requirements` (`id`, `rule_version_id`, `certification_id`, `cycle_months`, `total_credits_x100`, `annual_min_x100`, `annual_min_severity`, `fee_amount_cents`, `fee_currency`, `fee_period_months`, `fee_params`) VALUES ('giac@1/giac/gpen', 'giac@1', 'giac/gpen', 48, 3600, NULL, NULL, 49900, 'USD', 48, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `constraints` (`id`, `rule_version_id`, `certification_id`, `type`, `params`, `severity`) VALUES ('giac@1/con/001-any_of', 'giac@1', NULL, 'any_of', '{"of":[{"type":"cycle_total"},{"type":"recert_exam"}]}', 'hard') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `constraints` (`id`, `rule_version_id`, `certification_id`, `type`, `params`, `severity`) VALUES ('giac@1/con/002-fee_paid', 'giac@1', NULL, 'fee_paid', '{}', 'hard') ON CONFLICT DO NOTHING;
