-- Seed imi@1: generated by scripts/compile-catalog.ts from catalog/bodies/imi.yaml. Do not edit.
INSERT INTO `bodies` (`id`, `name`, `website`, `fee_scope`) VALUES ('imi', 'Identity Management Institute', 'https://identitymanagementinstitute.org', 'membership') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('imi/cipa', 'imi', 'Certified Identity Protection Advisor', 'CIPA', 'CE hour', 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('imi/cimp', 'imi', 'Certified Identity Management Professional', 'CIMP', 'CE hour', 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('imi/ciam', 'imi', 'Certified Identity and Access Manager', 'CIAM', 'CE hour', 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('imi/cige', 'imi', 'Certified Identity Governance Expert', 'CIGE', 'CE hour', 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `rule_versions` (`id`, `body_id`, `version`, `effective_from`, `source_url`, `source_title`, `verified_on`, `notes`) VALUES ('imi@1', 'imi', 1, '2025-01-01', 'https://identitymanagementinstitute.org/certification/', 'IMI — Identity Management Certification', '2026-09-12', 'Certifications stay active only while membership is renewed annually (fee scope membership). Fee encoded at the single-certificate rate; tiers in fee_params. Continuing education is stated as 60 hours per 3 years without a published activity table; hours are credited 1:1 (VERIFY B14 — activity list is thin; confirm with IMI by email if needed). The 3-month grace and $50 late fee are not modelled.') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_requirements` (`id`, `rule_version_id`, `certification_id`, `cycle_months`, `total_credits_x100`, `annual_min_x100`, `annual_min_severity`, `fee_amount_cents`, `fee_currency`, `fee_period_months`, `fee_params`) VALUES ('imi@1/imi/cipa', 'imi@1', 'imi/cipa', 36, 6000, NULL, NULL, 9500, 'USD', 12, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_requirements` (`id`, `rule_version_id`, `certification_id`, `cycle_months`, `total_credits_x100`, `annual_min_x100`, `annual_min_severity`, `fee_amount_cents`, `fee_currency`, `fee_period_months`, `fee_params`) VALUES ('imi@1/imi/cimp', 'imi@1', 'imi/cimp', 36, 6000, NULL, NULL, 9500, 'USD', 12, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_requirements` (`id`, `rule_version_id`, `certification_id`, `cycle_months`, `total_credits_x100`, `annual_min_x100`, `annual_min_severity`, `fee_amount_cents`, `fee_currency`, `fee_period_months`, `fee_params`) VALUES ('imi@1/imi/ciam', 'imi@1', 'imi/ciam', 36, 6000, NULL, NULL, 9500, 'USD', 12, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_requirements` (`id`, `rule_version_id`, `certification_id`, `cycle_months`, `total_credits_x100`, `annual_min_x100`, `annual_min_severity`, `fee_amount_cents`, `fee_currency`, `fee_period_months`, `fee_params`) VALUES ('imi@1/imi/cige', 'imi@1', 'imi/cige', 36, 6000, NULL, NULL, 9500, 'USD', 12, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `crediting_rules` (`id`, `rule_version_id`, `activity_type`, `body_label`, `basis`, `minutes_per_credit`, `credits_per_item_x100`, `rounding`, `category_key`, `cap_per_cycle_x100`, `cap_per_year_x100`, `cap_per_item_x100`, `evidence_required`, `applies_to_cert_id`) VALUES ('imi@1/cr/001-attend_training', 'imi@1', 'attend_training', 'Continuing education (hours)', 'per_minutes', 60, NULL, 'exact', NULL, NULL, NULL, NULL, 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `crediting_rules` (`id`, `rule_version_id`, `activity_type`, `body_label`, `basis`, `minutes_per_credit`, `credits_per_item_x100`, `rounding`, `category_key`, `cap_per_cycle_x100`, `cap_per_year_x100`, `cap_per_item_x100`, `evidence_required`, `applies_to_cert_id`) VALUES ('imi@1/cr/002-attend_conference', 'imi@1', 'attend_conference', 'Continuing education (hours)', 'per_minutes', 60, NULL, 'exact', NULL, NULL, NULL, NULL, 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `crediting_rules` (`id`, `rule_version_id`, `activity_type`, `body_label`, `basis`, `minutes_per_credit`, `credits_per_item_x100`, `rounding`, `category_key`, `cap_per_cycle_x100`, `cap_per_year_x100`, `cap_per_item_x100`, `evidence_required`, `applies_to_cert_id`) VALUES ('imi@1/cr/003-attend_webinar', 'imi@1', 'attend_webinar', 'Continuing education (hours)', 'per_minutes', 60, NULL, 'exact', NULL, NULL, NULL, NULL, 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `crediting_rules` (`id`, `rule_version_id`, `activity_type`, `body_label`, `basis`, `minutes_per_credit`, `credits_per_item_x100`, `rounding`, `category_key`, `cap_per_cycle_x100`, `cap_per_year_x100`, `cap_per_item_x100`, `evidence_required`, `applies_to_cert_id`) VALUES ('imi@1/cr/004-self_study_timed', 'imi@1', 'self_study_timed', 'Continuing education (hours)', 'per_minutes', 60, NULL, 'exact', NULL, NULL, NULL, NULL, 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `crediting_rules` (`id`, `rule_version_id`, `activity_type`, `body_label`, `basis`, `minutes_per_credit`, `credits_per_item_x100`, `rounding`, `category_key`, `cap_per_cycle_x100`, `cap_per_year_x100`, `cap_per_item_x100`, `evidence_required`, `applies_to_cert_id`) VALUES ('imi@1/cr/005-higher_education', 'imi@1', 'higher_education', 'Continuing education (hours)', 'per_minutes', 60, NULL, 'exact', NULL, NULL, NULL, NULL, 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `constraints` (`id`, `rule_version_id`, `certification_id`, `type`, `params`, `severity`) VALUES ('imi@1/con/001-cycle_total', 'imi@1', NULL, 'cycle_total', '{}', 'hard') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `constraints` (`id`, `rule_version_id`, `certification_id`, `type`, `params`, `severity`) VALUES ('imi@1/con/002-fee_paid', 'imi@1', NULL, 'fee_paid', '{}', 'hard') ON CONFLICT DO NOTHING;
