-- Seed microsoft@1: generated by scripts/compile-catalog.ts from catalog/bodies/microsoft.yaml. Do not edit.
INSERT INTO `bodies` (`id`, `name`, `website`, `fee_scope`) VALUES ('microsoft', 'Microsoft', 'https://learn.microsoft.com/credentials', 'none') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('microsoft/az-900', 'microsoft', 'Microsoft Certified Azure Fundamentals', 'AZ-900', 'credit', 0, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('microsoft/sc-900', 'microsoft', 'Microsoft Certified Security', 'SC-900', 'credit', 0, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('microsoft/az-104', 'microsoft', 'Microsoft Certified Azure Administrator Associate', 'AZ-104', 'credit', 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('microsoft/az-500', 'microsoft', 'Microsoft Certified Azure Security Engineer Associate', 'AZ-500', 'credit', 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('microsoft/sc-200', 'microsoft', 'Microsoft Certified Security Operations Analyst Associate', 'SC-200', 'credit', 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('microsoft/sc-100', 'microsoft', 'Microsoft Certified Cybersecurity Architect Expert', 'SC-100', 'credit', 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('microsoft/az-305', 'microsoft', 'Microsoft Certified Azure Solutions Architect Expert', 'AZ-305', 'credit', 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `rule_versions` (`id`, `body_id`, `version`, `effective_from`, `source_url`, `source_title`, `verified_on`, `notes`) VALUES ('microsoft@1', 'microsoft', 1, '2025-01-14', 'https://learn.microsoft.com/en-us/credentials/certifications/renew-your-microsoft-certification', 'Microsoft Certification Renewal (page updated 2025-01-14)', '2026-09-12', 'One-year validity for associate, expert, and specialty certifications; renew free by passing the online assessment any time in the six months before expiry (recert_exam). On success the certification extends one year from its expiration date. Fundamentals certifications never expire. No fee.') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_requirements` (`id`, `rule_version_id`, `certification_id`, `cycle_months`, `total_credits_x100`, `annual_min_x100`, `annual_min_severity`, `fee_amount_cents`, `fee_currency`, `fee_period_months`, `fee_params`) VALUES ('microsoft@1/microsoft/az-104', 'microsoft@1', 'microsoft/az-104', 12, 0, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_requirements` (`id`, `rule_version_id`, `certification_id`, `cycle_months`, `total_credits_x100`, `annual_min_x100`, `annual_min_severity`, `fee_amount_cents`, `fee_currency`, `fee_period_months`, `fee_params`) VALUES ('microsoft@1/microsoft/az-500', 'microsoft@1', 'microsoft/az-500', 12, 0, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_requirements` (`id`, `rule_version_id`, `certification_id`, `cycle_months`, `total_credits_x100`, `annual_min_x100`, `annual_min_severity`, `fee_amount_cents`, `fee_currency`, `fee_period_months`, `fee_params`) VALUES ('microsoft@1/microsoft/sc-200', 'microsoft@1', 'microsoft/sc-200', 12, 0, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_requirements` (`id`, `rule_version_id`, `certification_id`, `cycle_months`, `total_credits_x100`, `annual_min_x100`, `annual_min_severity`, `fee_amount_cents`, `fee_currency`, `fee_period_months`, `fee_params`) VALUES ('microsoft@1/microsoft/sc-100', 'microsoft@1', 'microsoft/sc-100', 12, 0, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_requirements` (`id`, `rule_version_id`, `certification_id`, `cycle_months`, `total_credits_x100`, `annual_min_x100`, `annual_min_severity`, `fee_amount_cents`, `fee_currency`, `fee_period_months`, `fee_params`) VALUES ('microsoft@1/microsoft/az-305', 'microsoft@1', 'microsoft/az-305', 12, 0, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `constraints` (`id`, `rule_version_id`, `certification_id`, `type`, `params`, `severity`) VALUES ('microsoft@1/con/001-recert_exam', 'microsoft@1', NULL, 'recert_exam', '{}', 'hard') ON CONFLICT DO NOTHING;
