-- Seed pmi@1: generated by scripts/compile-catalog.ts from catalog/bodies/pmi.yaml. Do not edit.
INSERT INTO `bodies` (`id`, `name`, `website`, `fee_scope`) VALUES ('pmi', 'Project Management Institute', 'https://www.pmi.org', 'none') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('pmi/pmp', 'pmi', 'Project Management Professional', 'PMP', 'PDU', 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('pmi/pmi-acp', 'pmi', 'PMI Agile Certified Practitioner', 'PMI-ACP', 'PDU', 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('pmi/capm', 'pmi', 'Certified Associate in Project Management', 'CAPM', 'PDU', 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `rule_versions` (`id`, `body_id`, `version`, `effective_from`, `source_url`, `source_title`, `verified_on`, `notes`) VALUES ('pmi@1', 'pmi', 1, '2026-04-01', 'https://www.pmi.org/-/media/pmi/documents/public/pdf/certifications/ccr-certification-requirements-handbook.pdf', 'PMI Continuing Certification Requirements (CCR) Handbook (last updated April 2026)', '2026-09-12', 'Three-year cycle from the exam pass date. Education is a minimum (35 / 18 / 9) with Talent Triangle sub-minimums (8/8/8, 4/4/4, 2/2/2); Giving Back is a maximum (25 / 12 / 6) with a sub-cap for working as a practitioner (8 / 4 / 2). One PDU = one hour, reported in 0.25 increments (floor_quarter chosen; handbook shows 15 min = 0.25). Suggested credits land in the parent category ''education'' or ''giving_back''; refine to the Talent Triangle area on the fan-out screen so the sub-minimums can be tracked. Renewal fee amount not published in the handbook — not encoded (VERIFY B10).') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `credit_categories` (`id`, `rule_version_id`, `key`, `name`, `parent_key`) VALUES ('pmi@1/education', 'pmi@1', 'education', 'Education', NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `credit_categories` (`id`, `rule_version_id`, `key`, `name`, `parent_key`) VALUES ('pmi@1/wow', 'pmi@1', 'wow', 'Ways of Working', 'education') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `credit_categories` (`id`, `rule_version_id`, `key`, `name`, `parent_key`) VALUES ('pmi@1/ps', 'pmi@1', 'ps', 'Power Skills', 'education') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `credit_categories` (`id`, `rule_version_id`, `key`, `name`, `parent_key`) VALUES ('pmi@1/ba', 'pmi@1', 'ba', 'Business Acumen', 'education') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `credit_categories` (`id`, `rule_version_id`, `key`, `name`, `parent_key`) VALUES ('pmi@1/giving_back', 'pmi@1', 'giving_back', 'Giving Back to the Profession', NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `credit_categories` (`id`, `rule_version_id`, `key`, `name`, `parent_key`) VALUES ('pmi@1/volunteering', 'pmi@1', 'volunteering', 'Volunteering', 'giving_back') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `credit_categories` (`id`, `rule_version_id`, `key`, `name`, `parent_key`) VALUES ('pmi@1/creating_knowledge', 'pmi@1', 'creating_knowledge', 'Creating Knowledge', 'giving_back') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `credit_categories` (`id`, `rule_version_id`, `key`, `name`, `parent_key`) VALUES ('pmi@1/practitioner', 'pmi@1', 'practitioner', 'Working as a Practitioner', 'giving_back') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_requirements` (`id`, `rule_version_id`, `certification_id`, `cycle_months`, `total_credits_x100`, `annual_min_x100`, `annual_min_severity`, `fee_amount_cents`, `fee_currency`, `fee_period_months`, `fee_params`) VALUES ('pmi@1/pmi/pmp', 'pmi@1', 'pmi/pmp', 36, 6000, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_requirements` (`id`, `rule_version_id`, `certification_id`, `cycle_months`, `total_credits_x100`, `annual_min_x100`, `annual_min_severity`, `fee_amount_cents`, `fee_currency`, `fee_period_months`, `fee_params`) VALUES ('pmi@1/pmi/pmi-acp', 'pmi@1', 'pmi/pmi-acp', 36, 3000, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `cert_requirements` (`id`, `rule_version_id`, `certification_id`, `cycle_months`, `total_credits_x100`, `annual_min_x100`, `annual_min_severity`, `fee_amount_cents`, `fee_currency`, `fee_period_months`, `fee_params`) VALUES ('pmi@1/pmi/capm', 'pmi@1', 'pmi/capm', 36, 1500, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `crediting_rules` (`id`, `rule_version_id`, `activity_type`, `body_label`, `basis`, `minutes_per_credit`, `credits_per_item_x100`, `rounding`, `category_key`, `cap_per_cycle_x100`, `cap_per_year_x100`, `cap_per_item_x100`, `evidence_required`, `applies_to_cert_id`) VALUES ('pmi@1/cr/001-attend_training', 'pmi@1', 'attend_training', 'Education — course or training', 'per_minutes', 60, NULL, 'floor_quarter', 'education', NULL, NULL, NULL, 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `crediting_rules` (`id`, `rule_version_id`, `activity_type`, `body_label`, `basis`, `minutes_per_credit`, `credits_per_item_x100`, `rounding`, `category_key`, `cap_per_cycle_x100`, `cap_per_year_x100`, `cap_per_item_x100`, `evidence_required`, `applies_to_cert_id`) VALUES ('pmi@1/cr/002-attend_conference', 'pmi@1', 'attend_conference', 'Education — organization meetings / events', 'per_minutes', 60, NULL, 'floor_quarter', 'education', NULL, NULL, NULL, 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `crediting_rules` (`id`, `rule_version_id`, `activity_type`, `body_label`, `basis`, `minutes_per_credit`, `credits_per_item_x100`, `rounding`, `category_key`, `cap_per_cycle_x100`, `cap_per_year_x100`, `cap_per_item_x100`, `evidence_required`, `applies_to_cert_id`) VALUES ('pmi@1/cr/003-attend_webinar', 'pmi@1', 'attend_webinar', 'Education — online or digital media', 'per_minutes', 60, NULL, 'floor_quarter', 'education', NULL, NULL, NULL, 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `crediting_rules` (`id`, `rule_version_id`, `activity_type`, `body_label`, `basis`, `minutes_per_credit`, `credits_per_item_x100`, `rounding`, `category_key`, `cap_per_cycle_x100`, `cap_per_year_x100`, `cap_per_item_x100`, `evidence_required`, `applies_to_cert_id`) VALUES ('pmi@1/cr/004-self_study_timed', 'pmi@1', 'self_study_timed', 'Education — read', 'per_minutes', 60, NULL, 'floor_quarter', 'education', NULL, NULL, NULL, 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `crediting_rules` (`id`, `rule_version_id`, `activity_type`, `body_label`, `basis`, `minutes_per_credit`, `credits_per_item_x100`, `rounding`, `category_key`, `cap_per_cycle_x100`, `cap_per_year_x100`, `cap_per_item_x100`, `evidence_required`, `applies_to_cert_id`) VALUES ('pmi@1/cr/005-read_book', 'pmi@1', 'read_book', 'Education — read', 'per_minutes', 60, NULL, 'floor_quarter', 'education', NULL, NULL, NULL, 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `crediting_rules` (`id`, `rule_version_id`, `activity_type`, `body_label`, `basis`, `minutes_per_credit`, `credits_per_item_x100`, `rounding`, `category_key`, `cap_per_cycle_x100`, `cap_per_year_x100`, `cap_per_item_x100`, `evidence_required`, `applies_to_cert_id`) VALUES ('pmi@1/cr/006-read_article', 'pmi@1', 'read_article', 'Education — read', 'per_minutes', 60, NULL, 'floor_quarter', 'education', NULL, NULL, NULL, 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `crediting_rules` (`id`, `rule_version_id`, `activity_type`, `body_label`, `basis`, `minutes_per_credit`, `credits_per_item_x100`, `rounding`, `category_key`, `cap_per_cycle_x100`, `cap_per_year_x100`, `cap_per_item_x100`, `evidence_required`, `applies_to_cert_id`) VALUES ('pmi@1/cr/007-higher_education', 'pmi@1', 'higher_education', 'Education — course or training', 'per_minutes', 60, NULL, 'floor_quarter', 'education', NULL, NULL, NULL, 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `crediting_rules` (`id`, `rule_version_id`, `activity_type`, `body_label`, `basis`, `minutes_per_credit`, `credits_per_item_x100`, `rounding`, `category_key`, `cap_per_cycle_x100`, `cap_per_year_x100`, `cap_per_item_x100`, `evidence_required`, `applies_to_cert_id`) VALUES ('pmi@1/cr/008-deliver_presentation', 'pmi@1', 'deliver_presentation', 'Giving back — share knowledge (presenting)', 'per_minutes', 60, NULL, 'floor_quarter', 'creating_knowledge', NULL, NULL, NULL, 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `crediting_rules` (`id`, `rule_version_id`, `activity_type`, `body_label`, `basis`, `minutes_per_credit`, `credits_per_item_x100`, `rounding`, `category_key`, `cap_per_cycle_x100`, `cap_per_year_x100`, `cap_per_item_x100`, `evidence_required`, `applies_to_cert_id`) VALUES ('pmi@1/cr/009-deliver_training', 'pmi@1', 'deliver_training', 'Giving back — share knowledge (teaching)', 'per_minutes', 60, NULL, 'floor_quarter', 'creating_knowledge', NULL, NULL, NULL, 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `crediting_rules` (`id`, `rule_version_id`, `activity_type`, `body_label`, `basis`, `minutes_per_credit`, `credits_per_item_x100`, `rounding`, `category_key`, `cap_per_cycle_x100`, `cap_per_year_x100`, `cap_per_item_x100`, `evidence_required`, `applies_to_cert_id`) VALUES ('pmi@1/cr/010-develop_content', 'pmi@1', 'develop_content', 'Giving back — create content', 'per_minutes', 60, NULL, 'floor_quarter', 'creating_knowledge', NULL, NULL, NULL, 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `crediting_rules` (`id`, `rule_version_id`, `activity_type`, `body_label`, `basis`, `minutes_per_credit`, `credits_per_item_x100`, `rounding`, `category_key`, `cap_per_cycle_x100`, `cap_per_year_x100`, `cap_per_item_x100`, `evidence_required`, `applies_to_cert_id`) VALUES ('pmi@1/cr/011-publish_article', 'pmi@1', 'publish_article', 'Giving back — create content', 'per_minutes', 60, NULL, 'floor_quarter', 'creating_knowledge', NULL, NULL, NULL, 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `crediting_rules` (`id`, `rule_version_id`, `activity_type`, `body_label`, `basis`, `minutes_per_credit`, `credits_per_item_x100`, `rounding`, `category_key`, `cap_per_cycle_x100`, `cap_per_year_x100`, `cap_per_item_x100`, `evidence_required`, `applies_to_cert_id`) VALUES ('pmi@1/cr/012-publish_book', 'pmi@1', 'publish_book', 'Giving back — create content', 'per_minutes', 60, NULL, 'floor_quarter', 'creating_knowledge', NULL, NULL, NULL, 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `crediting_rules` (`id`, `rule_version_id`, `activity_type`, `body_label`, `basis`, `minutes_per_credit`, `credits_per_item_x100`, `rounding`, `category_key`, `cap_per_cycle_x100`, `cap_per_year_x100`, `cap_per_item_x100`, `evidence_required`, `applies_to_cert_id`) VALUES ('pmi@1/cr/013-mentor', 'pmi@1', 'mentor', 'Giving back — volunteer (mentoring)', 'per_minutes', 60, NULL, 'floor_quarter', 'volunteering', NULL, NULL, NULL, 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `crediting_rules` (`id`, `rule_version_id`, `activity_type`, `body_label`, `basis`, `minutes_per_credit`, `credits_per_item_x100`, `rounding`, `category_key`, `cap_per_cycle_x100`, `cap_per_year_x100`, `cap_per_item_x100`, `evidence_required`, `applies_to_cert_id`) VALUES ('pmi@1/cr/014-volunteer', 'pmi@1', 'volunteer', 'Giving back — volunteer', 'per_minutes', 60, NULL, 'floor_quarter', 'volunteering', NULL, NULL, NULL, 1, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `constraints` (`id`, `rule_version_id`, `certification_id`, `type`, `params`, `severity`) VALUES ('pmi@1/con/001-cycle_total', 'pmi@1', NULL, 'cycle_total', '{}', 'hard') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `constraints` (`id`, `rule_version_id`, `certification_id`, `type`, `params`, `severity`) VALUES ('pmi@1/con/002-category_min', 'pmi@1', 'pmi/pmp', 'category_min', '{"category":"education","min":35}', 'hard') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `constraints` (`id`, `rule_version_id`, `certification_id`, `type`, `params`, `severity`) VALUES ('pmi@1/con/003-category_min', 'pmi@1', 'pmi/pmp', 'category_min', '{"category":"wow","min":8}', 'hard') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `constraints` (`id`, `rule_version_id`, `certification_id`, `type`, `params`, `severity`) VALUES ('pmi@1/con/004-category_min', 'pmi@1', 'pmi/pmp', 'category_min', '{"category":"ps","min":8}', 'hard') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `constraints` (`id`, `rule_version_id`, `certification_id`, `type`, `params`, `severity`) VALUES ('pmi@1/con/005-category_min', 'pmi@1', 'pmi/pmp', 'category_min', '{"category":"ba","min":8}', 'hard') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `constraints` (`id`, `rule_version_id`, `certification_id`, `type`, `params`, `severity`) VALUES ('pmi@1/con/006-category_max', 'pmi@1', 'pmi/pmp', 'category_max', '{"category":"giving_back","max":25}', 'hard') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `constraints` (`id`, `rule_version_id`, `certification_id`, `type`, `params`, `severity`) VALUES ('pmi@1/con/007-category_max', 'pmi@1', 'pmi/pmp', 'category_max', '{"category":"practitioner","max":8}', 'hard') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `constraints` (`id`, `rule_version_id`, `certification_id`, `type`, `params`, `severity`) VALUES ('pmi@1/con/008-category_min', 'pmi@1', 'pmi/pmi-acp', 'category_min', '{"category":"education","min":18}', 'hard') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `constraints` (`id`, `rule_version_id`, `certification_id`, `type`, `params`, `severity`) VALUES ('pmi@1/con/009-category_min', 'pmi@1', 'pmi/pmi-acp', 'category_min', '{"category":"wow","min":4}', 'hard') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `constraints` (`id`, `rule_version_id`, `certification_id`, `type`, `params`, `severity`) VALUES ('pmi@1/con/010-category_min', 'pmi@1', 'pmi/pmi-acp', 'category_min', '{"category":"ps","min":4}', 'hard') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `constraints` (`id`, `rule_version_id`, `certification_id`, `type`, `params`, `severity`) VALUES ('pmi@1/con/011-category_min', 'pmi@1', 'pmi/pmi-acp', 'category_min', '{"category":"ba","min":4}', 'hard') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `constraints` (`id`, `rule_version_id`, `certification_id`, `type`, `params`, `severity`) VALUES ('pmi@1/con/012-category_max', 'pmi@1', 'pmi/pmi-acp', 'category_max', '{"category":"giving_back","max":12}', 'hard') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `constraints` (`id`, `rule_version_id`, `certification_id`, `type`, `params`, `severity`) VALUES ('pmi@1/con/013-category_max', 'pmi@1', 'pmi/pmi-acp', 'category_max', '{"category":"practitioner","max":4}', 'hard') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `constraints` (`id`, `rule_version_id`, `certification_id`, `type`, `params`, `severity`) VALUES ('pmi@1/con/014-category_min', 'pmi@1', 'pmi/capm', 'category_min', '{"category":"education","min":9}', 'hard') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `constraints` (`id`, `rule_version_id`, `certification_id`, `type`, `params`, `severity`) VALUES ('pmi@1/con/015-category_min', 'pmi@1', 'pmi/capm', 'category_min', '{"category":"wow","min":2}', 'hard') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `constraints` (`id`, `rule_version_id`, `certification_id`, `type`, `params`, `severity`) VALUES ('pmi@1/con/016-category_min', 'pmi@1', 'pmi/capm', 'category_min', '{"category":"ps","min":2}', 'hard') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `constraints` (`id`, `rule_version_id`, `certification_id`, `type`, `params`, `severity`) VALUES ('pmi@1/con/017-category_min', 'pmi@1', 'pmi/capm', 'category_min', '{"category":"ba","min":2}', 'hard') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `constraints` (`id`, `rule_version_id`, `certification_id`, `type`, `params`, `severity`) VALUES ('pmi@1/con/018-category_max', 'pmi@1', 'pmi/capm', 'category_max', '{"category":"giving_back","max":6}', 'hard') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `constraints` (`id`, `rule_version_id`, `certification_id`, `type`, `params`, `severity`) VALUES ('pmi@1/con/019-category_max', 'pmi@1', 'pmi/capm', 'category_max', '{"category":"practitioner","max":2}', 'hard') ON CONFLICT DO NOTHING;
