-- Seed testout@1: generated by scripts/compile-catalog.ts from catalog/bodies/testout.yaml. Do not edit.
INSERT INTO `bodies` (`id`, `name`, `website`, `fee_scope`) VALUES ('testout', 'TestOut (CompTIA)', 'https://www.comptia.org', 'none') ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('testout/security-pro', 'testout', 'TestOut Security Pro', 'Security Pro', 'credit', 0, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('testout/network-pro', 'testout', 'TestOut Network Pro', 'Network Pro', 'credit', 0, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('testout/ethical-hacker-pro', 'testout', 'TestOut Ethical Hacker Pro', 'Ethical Hacker Pro', 'credit', 0, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('testout/pc-pro', 'testout', 'TestOut PC Pro', 'PC Pro', 'credit', 0, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('testout/linux-pro', 'testout', 'TestOut Linux Pro', 'Linux Pro', 'credit', 0, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `certifications` (`id`, `body_id`, `name`, `abbreviation`, `credit_unit_label`, `expires`, `retired_on`) VALUES ('testout/cyberdefense-pro', 'testout', 'TestOut CyberDefense Pro', 'CyberDefense Pro', 'credit', 0, NULL) ON CONFLICT DO NOTHING;
--> statement-breakpoint
INSERT INTO `rule_versions` (`id`, `body_id`, `version`, `effective_from`, `source_url`, `source_title`, `verified_on`, `notes`) VALUES ('testout@1', 'testout', 1, '2019-01-01', 'https://www.azed.gov/sites/default/files/2019/08/SecurityPro%20Fact%20Sheet%20Form.pdf', 'TestOut Security Pro Certification Fact Sheet (Arizona Department of Education copy)', '2026-09-12', 'No continuing education, no fee, no expiry. Both sources are secondary or indirect (VERIFY B13); the issuer''s own page no longer exists. Certifications are listed so the dashboard shows the full portfolio.') ON CONFLICT DO NOTHING;
